name: Deploy Frontend Petinder

# Dispara quando há push para a branch main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configuração do Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalar dependências
        working-directory: ./app-petinder
        run: npm install

      - name: Build do App Vite
        working-directory: ./app-petinder
        run: npm run build

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push da imagem
        uses: docker/build-push-action@v6
        with:
          context: ./app-petinder
          file: ./app-petinder/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/deploy-petinder:frontend-v1

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull da nova imagem do Docker Hub
        run: |
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/deploy-petinder:frontend-v1

      - name: Parar e remover container antigo (se existir)
        run: |
          sudo docker stop petinder-frontend || true
          sudo docker rm petinder-frontend || true

      - name: Subir novo container frontend
        run: |
          sudo docker run -d \
            --name petinder-frontend \
            --restart=always \
            -p 80:80 \
            ${{ secrets.DOCKERHUB_USERNAME }}/deploy-petinder:frontend-v1

      - name: Mostrar containers rodando
        run: sudo docker ps -a
